DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-5"
DEFAULT_GOOGLE_MODEL = "gemini-3-flash-preview"
DEFAULT_OPENAI_MODEL = "gpt-5-mini"
DEFAULT_OPENROUTER_MODEL = "z-ai/glm-4.7-flash"
DEFAULT_XAI_MODEL = "grok-4-1-fast-non-reasoning"
