[project]
dependencies = [
    "instructor>=1.11.3",
    "langchain>=1.0.2",
    "langchain-openai>=1.0.1",
    "pillow>=12.0.0",
    "regex>=2025.10.23",
    "rich>=14.2.0",
    "colorama>=0.4.6",
    "spargear>=0.2.17",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "langchain-core>=1.0.1",
]
name = "chatterer"
version = "0.2.2.dev1"
description = "The highest-level interface for various LLM APIs."
readme = "README.md"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]
include = ["chatterer", "chatterer.*"]

[tool.pyright]
typeCheckingMode = "strict"

[project.optional-dependencies]
dev = ["pyright>=1.1.401"]

# Tool
browser = ["playwright>=1.50.0"]
pdf = ["pymupdf>=1.25.4", "pypdf>=5.4.0"]
markdown = [
    "markitdown[all]>=0.1.1",
    "markdownify>=1.1.0",
    "commonmark>=0.9.1",
    "mistune>=3.1.3",
]
video = ["pydub>=0.25.1", "youtube-transcript-api>=1.0.3"]
windows = ["pywin32>=306 ; sys_platform == 'win32'"]
langchain = [
    "langchain-anthropic>=0.3.10",
    "langchain-google-genai>=2.1.1",
    "langchain-ollama>=0.3.0",
]

# Optional dependencies for different functionalities
standard = [
    "chatterer[langchain]",
    "chatterer[pdf]",
    "chatterer[markdown]",
    "chatterer[windows]",
]
all = [
    "chatterer[standard]",
    "chatterer[dev]",
    "chatterer[browser]",
    "chatterer[video]",

]

[project.scripts]
chatterer = "chatterer.examples.__main__:main"

[tool.uv]
package = true

[tool.ruff]
line-length = 120
